name: GitGoogleContainer
on:
  push:
jobs:
  build:
    #runs-on: ubuntu-latest
    runs-on: windows-2019
    steps:
      # - uses: actions/checkout@v2
      - name: Login in Docker
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_IO_TOKEN }}
      - name: Docker pull and push
        run: |
          #docker pull k8s.gcr.io/ingress-nginx/controller:v0.35.0  
          #docker tag  k8s.gcr.io/ingress-nginx/controller:v0.35.0  ghcr.io/zuoguocai/ingress-nginx/controller:v0.35.0       
          #docker push ghcr.io/zuoguocai/ingress-nginx/controller:v0.35.0
          docker pull sigwindowstools/flannel:0.12.0
          docker pull sigwindowstools/kube-proxy:v1.19.2
          docker images 
          docker tag  sigwindowstools/flannel:0.12.0  ghcr.io/zuoguocai/sigwindowstools/flannel:0.12.0       
          docker tag  sigwindowstools/kube-proxy:v1.19.2  ghcr.io/zuoguocai/sigwindowstools/kube-proxy:v1.19.2
          docker push ghcr.io/zuoguocai/sigwindowstools/flannel:0.12.0
          docker push ghcr.io/zuoguocai/sigwindowstools/kube-proxy:v1.19.2
          docker push ghcr.io/zuoguocai/sigwindowstools/kube-proxy:v1.19.2
